### ISSUE TITLE
Hangs when Fetching bot 1 of 379 (badge 200 of 200)

### ISSUE THREAD

**Issue by EvE-Player** [Rudokhvist/ASF-STM#20]
I have been experiencing a recurring issue with this script over the past few weeks. The problem occurs during the execution of the script when it reaches the step of "Fetching bot 1 of 379 (badge 200 of 200)." At this point, the script becomes unresponsive and fails to proceed any further. Even after waiting for an extended period of time, the script refuses to load beyond this specific stage.

  Any ideas as to why? 

Thank you

**Comment by Rudokhvist** [comment]
Thank you for report! Sadly right now I have some health issues and don't have time for active development, but I'll look into it as soon as I'll have some time.

**Comment by Rudokhvist** [comment]
Sorry for the delay. Had some time today to look into it. Can't reproduce it on my account, thanks you error message you provided I see where it crashes, but I don't understand why it crashes. What browser and userscript extension are you using? Do you have other userscripts running on that page?

**Comment by Rudokhvist** [comment]
Ok, it is indeed caused by that script, to be more precise - by older jQuery library that it uses. I'll update next version of ASF-STM to avoid that conflict. Thank you for your report.

> And also, when using the script now it's working, trying to match a massive inventory vs my large inventory it spits out the error:

You probably mean when you try to open trade window? Yes, I'm aware about this issue, and definitely want to do something about this, but so far not sure about the best approach for fix. And yes, it's happens when there is a lot of items to be traded for this match. I'll try to look at it again now, while I have some time. 

> Anyway, I'm glad to see you are hopefully doing better!

I'm still pretty busy, but at least some of my health issues are gone, feeling much better now. Thank you!
